import {
  Avatar,
  Card,
  Col,
  ContainerFixed,
  DescriptionItem,
  Descriptions,
  Divider,
  Link,
  Row,
  Space,
  Text,
  Title,
} from "@cv/components";
import { ContactWithMe } from "@cv/compositions";
import { EBreakpoint, EDirectionType } from "@cv/core";
import { Inter } from "next/font/google";
import Head from "next/head";
import AcademicQualifications from "src/compositions/academic-qualifications";
import DeeptechCompany from "src/compositions/deeptech-company";
import PersonalExperience from "src/compositions/personal-experience";
import PersonalInformation from "src/compositions/personal-information";
import PersonalSummary from "src/compositions/personal-summary";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Le Quoc Thinh - Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerFixed position="center" breakpoint={EBreakpoint.LG}>
        <Card>
          <Row>
            <Col span={11}>
              <PersonalInformation />
            </Col>
            <Col span={9} offset={4}>
              <ContactWithMe />
            </Col>
          </Row>
          <PersonalSummary />
          <DeeptechCompany />
          <PersonalExperience />
        </Card>
      </ContainerFixed>
    </>
  );
}
